// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_DataDocument_Export
#define _H_DataDocument_Export

static const JUtf8Byte* kExportMenuStr =
"* %i __Reload::DataDocument %l"
;

#include "DataDocument-Export-enum.h"


static void ConfigureExportMenu(JXTextMenu* menu, const int offset = 0) {
};

#endif
