// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_FitDirector_Fit_enum
#define _H_FitDirector_Fit_enum

enum {
	kNonLinearCmd=1,
	kPolyCmd,
	kRemoveFitCmd,
	kFitCmd,
	kRefitCmd,
	kShowStartCmd,
	kTestFitCmd,
	kPlotCmd,
	kShowHistoryCmd,
	kPrintCmd,
	kCloseCmd,
};

#endif
