// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_FitDirector_Fit
#define _H_FitDirector_Fit

static const JUtf8Byte* kFitMenuStr =
"* %i NewNonLinear::FitDirector"
"|* %i NewPoly::FitDirector"
"|* %i RemoveFit::FitDirector %l"
"|* %i Fit::FitDirector"
"|* %i ReFit::FitDirector %l"
"|* %b %i ShowStartValues::FitDirector"
"|* %i TestFit::FitDirector %l"
"|* %i Plot::FitDirector"
"|* %i ShowHistory::FitDirector"
"|* %i Print::FitDirector %l"
"|* %i Close::FitDirector"
;

#include "FitDirector-Fit-enum.h"

#ifndef _H_jx_af_image_jx_jx_file_print
#define _H_jx_af_image_jx_jx_file_print
#include <jx-af/image/jx/jx_file_print.xpm>
#endif

static void ConfigureFitMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts("#f");
	}
	menu->SetItemImage(kPrintCmd + offset, jx_file_print);
};

#endif
