// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_Generic_Preferences_enum
#define _H_Generic_Preferences_enum

enum {
	kEditToolBarCmd=1,
	kEditMacWinPrefsCmd,
	kSaveWindowSizeCmd,
};

#endif
