// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_HistoryDir_File
#define _H_HistoryDir_File

static const JUtf8Byte* kFileMenuStr =
"* %i __SaveSession::HistoryDir"
"|* %i __SaveSessionAs::HistoryDir %l"
"|* %i __SaveSessionWindowSize::HistoryDir %l"
"|* %i __Print::HistoryDir %l"
"|* %i __Close::HistoryDir"
"|* %i __Quit::HistoryDir"
;

#include "HistoryDir-File-enum.h"

#ifndef _H_jx_af_image_jx_jx_file_save
#define _H_jx_af_image_jx_jx_file_save
#include <jx-af/image/jx/jx_file_save.xpm>
#endif
#ifndef _H_jx_af_image_jx_jx_file_print
#define _H_jx_af_image_jx_jx_file_print
#include <jx-af/image/jx/jx_file_print.xpm>
#endif

static void ConfigureFileMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts("#f");
	}
	menu->SetItemImage(kSaveCmd + offset, jx_file_save);
	menu->SetItemImage(kPrintCmd + offset, jx_file_print);
};

#endif
