// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_HistoryDir_File_enum
#define _H_HistoryDir_File_enum

enum {
	kSaveCmd=1,
	kSaveAsCmd,
	kSaveWindowSizeCmd,
	kPrintCmd,
	kCloseCmd,
	kQuitCmd,
};

#endif
