/******************************************************************************
 MDIServer.h

	Interface for the MDIServer class

	Copyright (C) 1999 by Glenn W. Bach.
	
	Base code generated by Codemill v0.1.0

 *****************************************************************************/

#ifndef _H_MDIServer
#define _H_MDIServer

#include <jx-af/jx/JXMDIServer.h>

class PlotApp;

class MDIServer : public JXMDIServer
{
public:

	MDIServer(PlotApp* app);
	virtual ~MDIServer();

protected:

	virtual void	HandleMDIRequest(const JString& dir,
									 const JPtrArray<JString>& argList) override;

//	virtual void	Receive(JBroadcaster* sender, const Message& message) override;

private:

	PlotApp*	itsApp;
};

#endif
