// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_PlotDirector_Plot_enum
#define _H_PlotDirector_Plot_enum

enum {
	kPageSetupCmd=1,
	kPrintCmd,
	kPrintSessionCmd,
	kPrintPlotEPSCmd,
	kPrintMarksEPSCmd,
	kCloseCmd,
};

#endif
