// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_PlotDirector_Plot
#define _H_PlotDirector_Plot

static const JUtf8Byte* kPlotMenuStr =
"* %i __PageSetup::PlotDirector"
"|* %i __Print::PlotDirector"
"|* %i __PrintSession::PlotDirector %l"
"|* %i __PrintPlotAsEPS::PlotDirector"
"|* %i __PrintMarksAsEPS::PlotDirector %l"
"|* %i __Close::PlotDirector"
;

#include "PlotDirector-Plot-enum.h"

#ifndef _H_jx_af_image_jx_jx_file_print
#define _H_jx_af_image_jx_jx_file_print
#include <jx-af/image/jx/jx_file_print.xpm>
#endif

static void ConfigurePlotMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts("#p");
	}
	menu->SetItemImage(kPrintCmd + offset, jx_file_print);
};

#endif
