// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_PlotApp_Help_enum
#define _H_PlotApp_Help_enum

enum {
	kHelpAboutCmd=1,
	kHelpTOCCmd,
	kHelpWindowCmd,
	kHelpChangeLogCmd,
	kHelpCreditsCmd,
};

#endif
