// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_PlotDirector_Analysis
#define _H_PlotDirector_Analysis

static const JUtf8Byte* kAnalysisMenuStr =
"* %i __PlotFunction::PlotDirector %l"
"|* %i __OpenFitWindow::PlotDirector %l"
"|* %i __FitParameters::PlotDirector"
"|* %i __ResidualPlots::PlotDirector"
;

#include "PlotDirector-Analysis-enum.h"


static void ConfigureAnalysisMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts("#a");
	}
};

#endif
