/******************************************************************************
 PrefsMgr.h

	Interface for the PrefsMgr class

	Copyright (C) 1998 by Glenn W. Bach.

	Base code generated by Codemill v0.1.0

 *****************************************************************************/

#ifndef _H_PrefsMgr
#define _H_PrefsMgr

#include <jx-af/jx/JXPrefsManager.h>
#include <jx-af/jcore/JPtrArray.h>
#include <jx-af/jcore/JString.h>

class JXWindow;
class JXPTPrinter;
class FitDirector;

enum
{
	kDelimiterPrefsID = 1,
	kFileModulePrefsID,
	kProgramVersionID,
	kPlotWindowSizePrefsID,
	kTableWindowSizePrefsID,
	kPTPrinterSetupID,
	kDataToolBarID,
	kFitToolBarID,
	kFitManagerID,
	kFitDirectorID,
	kChooseSaveFilePrefsID,
	kVersionCheckID
};

class PrefsMgr : public JXPrefsManager
{
public:

	PrefsMgr(bool* isNew);
	~PrefsMgr() override;

	JString	GetGloveVersionStr() const;

	void	WritePrinterSetup(JXPTPrinter* printer);
	void	ReadPrinterSetup(JXPTPrinter* printer);

	void	WriteFitDirectorSetup(FitDirector* dir);
	void	ReadFitDirectorSetup(FitDirector* dir);

protected:

	void	UpgradeData(const bool isNew, const JFileVersion currentVersion) override;

private:

	void	GetWindowSize(const JPrefID id, JXWindow* window) const;
	void	SaveWindowSize(const JPrefID id, JXWindow* window);
};

#endif
