// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_RaggedFloatTable_Data_enum
#define _H_RaggedFloatTable_Data_enum

enum {
	kPlotCmd=1,
	kPlotVectorCmd,
	kTransCmd,
	kGenerateRangeColCmd,
	kGenerateIncrementColCmd,
	kDataModuleCmd,
};

#endif
