// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_RaggedFloatTable_Module
#define _H_RaggedFloatTable_Module

static const JUtf8Byte* kModuleMenuStr =
"* %i __Reload::RaggedFloatTable %l"
;

#include "RaggedFloatTable-Module-enum.h"


static void ConfigureModuleMenu(JXTextMenu* menu, const int offset = 0) {
};

#endif
