// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_RaggedFloatTable_Edit_enum
#define _H_RaggedFloatTable_Edit_enum

enum {
	kUndoCmd=1,
	kRedoCmd,
	kCutCmd,
	kCopyCmd,
	kPasteCmd,
	kSpecialPasteCmd,
	kInsertCmd,
	kDuplicateCmd,
	kDeleteCmd,
};

#endif
